### ISSUE TITLE
OraclizeAPI not compatible with solc ver > 4.0

### ISSUE THREAD

**Issue by makoto** [oraclize/ethereum-api#2]
When I try to compile with Truffle 2.0.1 which uses solc >4.0 it raises multiple compilation errors.
1. `Error: Expected token Semicolon got 'RBrace'`

This is the due to the fact that you now have to append semicolon like `_;` in modifier.
1.  `Error: Member "value" not found or not visible after argument-dependent lookup`

After fixing #1, I still get the following errors.

```
OraclizeI.sol:97:16: Error: Member "value" not found or not visible after argument-dependent lookup in function (uint256,string memory,string memory) returns (bytes32) - did you forget the "payable" modifier?
        return oraclize.query.value(price)(0, datasource, arg);
               ^------------------^
```

**Comment by axic** [comment]
For the second issue, the important part of the error is `did you forget the "payable" modifier?`

**Comment by marcogiglio** [comment]
As you can see [here](https://github.com/oraclize/ethereum-api/blob/master/oraclizeAPI_0.4.sol), we have solidity 0.4 compatible version
